print("Enter any two numbers:")
a=int(input())
b=int(input())
print("the value of :",a,"+",b,"=",a+b)
print("the value of :",a,"/",b,"=",a/b)
print("the value of :",a,"*",b,"=",a*b)
print("the value of :",a,"%",b,"=",a%b)
print("the value of :",a,"^",b,"=",a**b)
print("the value of :",a,"-",b,"=",a-b)
